// Generated by gencpp from file question_one/input.msg
// DO NOT EDIT!


#ifndef QUESTION_ONE_MESSAGE_INPUT_H
#define QUESTION_ONE_MESSAGE_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace question_one
{
template <class ContainerAllocator>
struct input_
{
  typedef input_<ContainerAllocator> Type;

  input_()
    : vector()
    , angles()
    , d(0.0)  {
      vector.assign(0.0);

      angles.assign(0.0);
  }
  input_(const ContainerAllocator& _alloc)
    : vector()
    , angles()
    , d(0.0)  {
  (void)_alloc;
      vector.assign(0.0);

      angles.assign(0.0);
  }



   typedef boost::array<double, 3>  _vector_type;
  _vector_type vector;

   typedef boost::array<double, 3>  _angles_type;
  _angles_type angles;

   typedef double _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::question_one::input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::question_one::input_<ContainerAllocator> const> ConstPtr;

}; // struct input_

typedef ::question_one::input_<std::allocator<void> > input;

typedef boost::shared_ptr< ::question_one::input > inputPtr;
typedef boost::shared_ptr< ::question_one::input const> inputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::question_one::input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::question_one::input_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::question_one::input_<ContainerAllocator1> & lhs, const ::question_one::input_<ContainerAllocator2> & rhs)
{
  return lhs.vector == rhs.vector &&
    lhs.angles == rhs.angles &&
    lhs.d == rhs.d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::question_one::input_<ContainerAllocator1> & lhs, const ::question_one::input_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace question_one

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::question_one::input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::question_one::input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question_one::input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::question_one::input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question_one::input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::question_one::input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::question_one::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b13874c5ea905eae4aac5b1fd6887b8e";
  }

  static const char* value(const ::question_one::input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb13874c5ea905eaeULL;
  static const uint64_t static_value2 = 0x4aac5b1fd6887b8eULL;
};

template<class ContainerAllocator>
struct DataType< ::question_one::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "question_one/input";
  }

  static const char* value(const ::question_one::input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::question_one::input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] vector\n"
"float64[3] angles\n"
"float64 d\n"
;
  }

  static const char* value(const ::question_one::input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::question_one::input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vector);
      stream.next(m.angles);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::question_one::input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::question_one::input_<ContainerAllocator>& v)
  {
    s << indent << "vector[]" << std::endl;
    for (size_t i = 0; i < v.vector.size(); ++i)
    {
      s << indent << "  vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vector[i]);
    }
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUESTION_ONE_MESSAGE_INPUT_H
